=== postmanlabs/schemas/schemas/draft-04/v1.0.0/collection.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://schema.getpostman.com/json/collection/v1.0.0/",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Every collection is identified by the unique value of this field. The value of this field is usually easiest to generate using a [UID](https://tools.ietf.org/html/rfc4122#section-4.4%29) generator function. If you already have a collection, it is recommended that you maintain the same id since changing the id usually implies that this is a different collection than it was originally."
    },
    "name": {
      "type": "string",
      "description": "A collection's friendly name is defined by this field. You would want to set this field to a value that would allow you to easily identify this collection among a bunch of other collections, as such outlining its usage or content."
    },
    "description": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "description": "Provide a long description of this collection using this field. This field supports markdown syntax to better format the description."
    },
    "variables": {
      "oneOf": [
        {
          "$ref": "#/definitions/variable-list"
        },
        {
          "type": "null"
        }
      ]
    },
    "order": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "description": "The order array ensures that your requests and folders don't randomly get shuffled up. It holds a sequence of [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) corresponding to folders and requests.\n *Note that if a folder ID or a request ID (if the request is not already part of a folder) is not included in the order array, the request or the folder will not show up in the collection.*"
    },
    "folders_order": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "description": "The folders order array ensures that your requests and folders don't randomly get shuffled up. It holds a sequence of [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) corresponding to folders and requests.\n *Note that if a folder ID or a request ID (if the request is not already part of a folder) is not included in the order array, the request or the folder will not show up in the collection.*"
    },
    "folders": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/folder"
      },
      "description": "Folders are the way to go if you want to group your requests and to keep things organised. Folders can also be useful in sequentially requesting a part of the entire collection by using [Postman Collection Runner](https://www.getpostman.com/docs/jetpacks_running_collections) or [Newman](https://github.com/postmanlabs/newman) on a particular folder."
    },
    "timestamp": {
      "type": "number",
      "multipleOf": 1
    },
    "requests": {
      "type": "array",
      "description": "",
      "items": {
        "$ref": "#/definitions/request"
      }
    },
    "events": {
      "$ref": "#/definitions/event-list"
    },
    "auth": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/definitions/auth"
        }
      ]
    },
    "protocolProfileBehavior": {
      "$ref": "#/definitions/protocol-profile-behavior"
    }
  },
  "required": [
    "id",
    "name",
    "order",
    "requests"
  ]
}

=== postmanlabs/schemas/examples/draft-07/v1.0.0/formdata-body.json
{
  "id": "5adbd3b7-80cb-43cc-bf1e-8578ab3c9b15",
  "name": "formdata-body",
  "order": [
    "844470c1-2017-4a08-b322-bc9a037d8cb5"
  ],
  "folders_order": [],
  "folders": [],
  "requests": [
    {
      "id": "844470c1-2017-4a08-b322-bc9a037d8cb5",
      "name": "R1",
      "url": "https://postman-echo.com/post",
      "data": [
        {
          "key": "text",
          "value": "textValue",
          "description": "",
          "type": "text"
        },
        {
          "key": "file",
          "type": "file",
          "value": null
        },
        {
          "key": "file",
          "type": "file",
          "value": ""
        },
        {
          "key": "file",
          "type": "file",
          "value": []
        }
      ],
      "headers": "",
      "dataMode": "params",
      "method": "POST",
      "collectionId": "5adbd3b7-80cb-43cc-bf1e-8578ab3c9b15"
    }
  ]
}
